from PrawnView.ProcesadoImagen.LeeImagen import LeeImagen
from PrawnView.ProcesadoImagen.EntradaZip import EntradaZip
from PrawnView.ProcesadoImagen.TratamientoDeImagen import TratamientoDeImagen
from PrawnView.ProcesadoImagen.TratamientoRegiones import TratamientoRegiones
from PrawnView.ProcesadoImagen.ProcesadorImagenAutomatico import ProcesadorImagenAutomatico
